defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: src.agent.train.TrainAgent

logdir: ${oc.env:VLA_LOG_DIR}/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
seed: 42
name: train_vla
device: cuda

dataset_mix: oxe_simple
data_path: /n/fs/llm-unc/data/resize_224
pretrained_model_path: /n/fs/llm-unc/.cache/paligemma-3b-pt-224

num_inference_steps: 10
final_action_clip_value:

cond_steps: 1
horizon_steps: 4
image_shape: [3, 224, 224]
action_dim: 20
proprio_dim: 20

image_token_index: 257152
ignore_index: -100
vocab_size: 257216
pad_token_id: 0
use_lm_head: False
max_seq_len: 512  # image + text

image_text_hidden_size: 2048  # gemma
proprio_hidden_size: 512
action_hidden_size: 1024

vision:
  _target_: src.model.paligemma.siglip.SiglipVisionModel
  config:
    hidden_size: 1152 # siglip
    intermediate_size: 4304
    num_hidden_layers: 27
    num_attention_heads: 16
    num_channels: 3
    image_size: ${image_shape[1]}
    patch_size: 14
    layer_norm_eps: 1e-6
    attention_dropout: 0.0
    num_image_tokens: 256

vision_projector:
  _target_: src.model.paligemma.siglip.PaliGemmaMultiModalProjector
  config:
    vision_config:
      hidden_size: 1152
      projection_dim: ${image_text_hidden_size}

joint:
  _target_: src.model.vla.modules.JointModel
  config:
    hidden_sizes:
      - ${image_text_hidden_size}
      - ${proprio_hidden_size}
      - ${action_hidden_size}
    intermediate_sizes:
      - 16384 # gemma
      - 1024
      - 4096
    #
    num_hidden_layers: 18
    num_attention_heads: 8
    num_key_value_heads: 1
    head_dim: 256
    max_position_embeddings: 8192
    rms_norm_eps: 1e-6
    rope_theta: 10000.0
    attention_bias: False
    attention_dropout: 0.0
    pad_token_id: ${pad_token_id}
